[build-system]
requires = [
    "setuptools>=61.0",  
<<<<<<< HEAD
    "torch>=2.1.0",
=======
    "torch>=2.5.1",
>>>>>>> 2b90b9f5ceec907a1c18123530e92e794ad901a4
    ]
build-backend = "setuptools.build_meta"
